### ISSUE TITLE
Shared Assessment

### ISSUE THREAD

**Issue by zjvv** [abreio/Abre-Assessments#8] opened 2017-11-15 21:07 UTC
When an assessment is shared with someone, they get the following options:
- Copy
- Build
- Results

What's not available is "Give". Is this intentional? Are we thinking we want people to copy before building? (And if so - why include build)?

**Comment by hcsdrose** [comment] 2017-11-15 21:13
This was originally done by design so that the results were linked to individual teachers and not lumped under one assessment ID. However due to the modified views we now offer for results this shouldn't be an issue to allow shared assessments to be given with the same shared link.

I can't think of any reason at the moment this would cause an issue. Should we add it?

**Comment by zjvv** [comment] 2017-11-15 21:18
We should. Would help with the Short Cycles people are creating. Those aren't technically "district assessment".

**Comment by hcsdrose** [comment] 2017-11-15 21:23
Will add this in the next release.

**Comment by hcsdrose** [comment] 2017-11-16 13:29
This issue was that if we allow "Give" and it's a district assessment then someone who was an editor would be able to give the assessment without using Guided Learning. This can be fixed however by only showing "Give" for assessments that are not district assessments. Will add this in next release.

**Comment by hcsdrose** [comment] 2017-11-16 15:37
Fixed in 1.3.6

**Closed by hcsdrose** 2017-11-16 15:37 UTC
Labels: question
